name: CI/CD for Node.js App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies and run tests
        run: |
          npm install
          npm test
          
      - name: Build Docker image (locally)
        run: docker build -t nodejs-app .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            # --- START of Deployment Script on EC2 Instance ---

            # 1. Install Git on the EC2 instance (if not already installed)
            # This fixes the "git: command not found" error
            sudo yum install git -y

            # 2. Stop and forcefully remove the existing container
            # The -f flag stops and removes the container in one go.
            # "|| true" ensures the script doesn't fail if the container doesn't exist.
            docker rm -f nodejs-app || true

            # 3. Handle the git repository state on the EC2 instance
            # This robust check ensures the repository is always in a good state.
            # It will pull if valid, or re-clone if it's missing or corrupted.
            cd /home/ec2-user || exit 1  # Navigate to the user's home directory
            
            if [ -d "app" ] && git -C app rev-parse --is-inside-work-tree > /dev/null 2>&1; then
              echo "App directory exists and is a valid Git repo. Pulling latest code..."
              cd app || exit 1
              git pull
            else
              echo "App directory is missing or corrupted. Re-cloning the repository."
              # Remove the existing directory to ensure a clean clone
              rm -rf app
              # You MUST replace the placeholder URL below with your actual repository URL
              git clone https://github.com/kingakwa/my-nodejs-app.git app
              cd app || exit 1
            fi

            # 4. Build the new Docker image from the latest code
            # This fixes the "Dockerfile: no such file or directory" error
            docker build -t nodejs-app .

            # 5. Run the new container, exposing port 3000
            if docker run -d -p 3000:3000 --name nodejs-app nodejs-app; then
              echo "✅ Deployment successful"
            else
              echo "❌ Deployment failed"
            fi
            
            # --- END of Deployment Script on EC2 Instance ---
