# First, install Git if it's not already there
sudo yum install git -y

# Stop and remove old containers and images (errors are expected on first run)
docker stop nodejs-app || true
docker rm nodejs-app || true
docker rmi nodejs-app || true

# Prepare the deployment directory
cd /home/ec2-user || mkdir /home/ec2-user && cd /home/ec2-user
if [ ! -d "app" ]; then
  echo "Cloning the repository for the first time..."
  git clone https://github.com/kingakwa/my-nodejs-app.git app
fi
cd app || exit
git pull

# Build and run the new Docker image
docker build -t nodejs-app .
if docker run -d -p 3000:3000 --name nodejs-app nodejs-app; then
  echo "✅ Deployment successful"
else
  echo "❌ Deployment failed"
fi
